// Copyright (c) Microsoft. All rights reserved.
package com.microsoft.semantickernel.connectors.memory.jdbc;

import java.sql.PreparedStatement;
import java.util.List;

public interface JDBCVectorStoreQueryHandler<Record> {
    /**
     * Formats a query to get records from the database.
     *
     * @param numberOfKeys the number of keys to get records for
     * @return the formatted query
     */
    String formatGetQuery(int numberOfKeys);

    /**
     * Formats a query to delete records from the database.
     *
     * @param numberOfKeys the number of keys to delete records for
     * @return the formatted query
     */
    String formatDeleteQuery(int numberOfKeys);

    /**
     * Formats a query to upsert records in the database.
     *
     * @return the formatted query
     */
    String formatUpsertQuery();

    /**
     * Configures the values for a get query generated by {@link #formatGetQuery(int)}.
     *
     * @param statement the prepared statement
     * @param keys the keys to get records for
     * @param collectionName the name of the collection
     */
    void configureStatementGetQuery(PreparedStatement statement, List<String> keys,
        String collectionName);

    /**
     * Configures the values for a delete query generated by {@link #formatDeleteQuery(int)}.
     *
     * @param statement the prepared statement
     * @param keys the keys to delete records for
     * @param collectionName the name of the collection
     */
    void configureStatementDeleteQuery(PreparedStatement statement, List<String> keys,
        String collectionName);

    /**
     * Configures the values for an upsert query generated by {@link #formatUpsertQuery()}.
     *
     * @param statement the prepared statement
     * @param data the record to upsert
     * @param collectionName the name of the collection
     * @return the key of the record
     */
    String configureStatementUpsertQuery(PreparedStatement statement, Record data,
        String collectionName);

}
